In [80]:
import pandas as pd

In [81]:
df=pd.read_csv(r"C:\Users\hetpa\OneDrive\Desktop\heart_modif.csv")

In [82]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168.0,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155.0,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125.0,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161.0,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106.0,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164.0,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141.0,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118.0,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159.0,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113.0,0,1.4,1,1,3,0

In [83]:
df.shape

(1025, 14)

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   object
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   978 non-null    float64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(2), int64(11), object(1)
memory usage: 112.2+ KB

In [85]:
df['chol'].unique()

array(['212', '203', '174', '294', '248', '318', '289', '249', '286',
       '149', '341', '210', '298', '204', '308', '266', '244', '211',
       '185', '223', '208', '252', '209', 'fff', '233', '319', '256',
       '327', '169', '131', '269', '196', '231', '213', '271', '263',
       '229', '360', '258', '330', '342', '226', '228', '278', '230',
       '283', '241', '175', '188', '217', '193', '245', '232', '299',
       '288', '197', '315', '215', '164', '326', '207', '177', '257',
       '255', '187', '201', '220', '268', '267', '236', '303', '282',
       '126', '309', '186', '275', '281', '206', '335', '218', '307',
       '254', '295', '417', '260', '240', '302', '192', '225', '325',
       '235', '274', '234', '182', '167', '172', '321', '300', '199',
       '564', '157', '304', '222', '184', '354', '160', '247', '239',
       '246', '409', '293', '180', '250', '221', '200', '227', '243',
       '311', '261', '242', '205', '306', '219', '353', '198', '394',
       '183', '237', '224', '265', '313', '340', '259', '270', '216',
       '264', '276', '322', '214', '273', '253', '176', '284', '305',
       '168', '407', '290', '277', '262', '195', '166', '178', '141'],
      dtype=object)

In [86]:
df['chol']=pd.to_numeric(df['chol'],errors='coerce')

In [87]:
df['chol'].dtype

dtype('float64')

In [88]:
df['chol'].isnull().sum()

np.int64(1)

In [89]:
df['chol']=df['chol'].fillna(df['chol'].median())

In [90]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212.0,0,1,168.0,0,1.0,2,2,3,0
1,53,1,0,140,203.0,1,0,155.0,1,3.1,0,0,3,0
2,70,1,0,145,174.0,0,1,125.0,1,2.6,0,0,3,0
3,61,1,0,148,203.0,0,1,161.0,0,0.0,2,1,3,0
4,62,0,0,138,294.0,1,1,106.0,0,1.9,1,3,2,0

In [91]:
df['thalach']=df['thalach'].fillna(df['thalach'].median())

In [92]:
df['thalach'].isna().sum()

np.int64(0)

In [93]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212.0,0,1,168.0,0,1.0,2,2,3,0
1,53,1,0,140,203.0,1,0,155.0,1,3.1,0,0,3,0
2,70,1,0,145,174.0,0,1,125.0,1,2.6,0,0,3,0
3,61,1,0,148,203.0,0,1,161.0,0,0.0,2,1,3,0
4,62,0,0,138,294.0,1,1,106.0,0,1.9,1,3,2,0

In [94]:
from sklearn.model_selection import train_test_split

In [95]:
x=df.drop(columns='target')
y=df['target']

In [96]:
print(x.columns)

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')

In [97]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [98]:
from sklearn.preprocessing import StandardScaler

In [99]:
scaler=StandardScaler()

In [100]:
x_scaled=scaler.fit_transform(x)

In [101]:
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=42)

In [102]:
from sklearn.linear_model import LogisticRegression

In [103]:
model=LogisticRegression()

In [104]:
model.fit(x_train,y_train)

LogisticRegression()

In [105]:
y_pred=model.predict(x_test)

In [106]:
from sklearn.metrics import accuracy_score

In [107]:
accuracy=accuracy_score(y_test,y_pred)

In [108]:
print("Your model accuracy score is",accuracy)

Your model accuracy score is 0.7951219512195122

In [109]:
import pickle

In [110]:
with open("heart_disease.pkl",'wb') as f:
    pickle.dump(model,f)

In [111]:
with open("scaler.pkl",'wb') as f:
    pickle.dump(scaler,f)